"""empty message

Revision ID: fe6f57ee8e31
Revises: 
Create Date: 2023-05-18 02:39:29.955561

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fe6f57ee8e31'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('building',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('Zip', sa.Text(), nullable=True),
    sa.Column('Type', sa.Text(), nullable=True),
    sa.Column('cooperate', sa.Boolean(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('scrape_city', sa.Text(), nullable=True),
    sa.Column('address_full', sa.Text(), nullable=True),
    sa.Column('media_count', sa.Integer(), nullable=True),
    sa.Column('ts', postgresql.TSVECTOR(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('building_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.Text(), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('pet_policy', sa.Text(), nullable=True),
    sa.Column('amenities', sa.JSON(), nullable=True),
    sa.Column('neighborhood_name', sa.Text(), nullable=True),
    sa.Column('neighborhood_area', sa.Text(), nullable=True),
    sa.Column('washer_dryer', sa.Text(), nullable=True),
    sa.Column('no_of_units', sa.Integer(), nullable=True),
    sa.Column('balcony', sa.Text(), nullable=True),
    sa.Column('parking', sa.Text(), nullable=True),
    sa.Column('short_term_lease', sa.Text(), nullable=True),
    sa.Column('tour_sunday', sa.Boolean(), nullable=True),
    sa.Column('cooperation_percentage', sa.Float(), nullable=True),
    sa.Column('concession_months_additional', sa.BigInteger(), nullable=True),
    sa.Column('scraper_complete', sa.Boolean(), nullable=True),
    sa.Column('website_reachable', sa.Boolean(), nullable=True),
    sa.Column('website_needs_ui_navigation', sa.Boolean(), nullable=True),
    sa.Column('website_data_in_images', sa.Boolean(), nullable=True),
    sa.Column('data_source', sa.Text(), nullable=True),
    sa.Column('year_built', sa.Text(), nullable=True),
    sa.Column('nearest_grocery_store', sa.JSON(), nullable=True),
    sa.Column('nearest_convenience_store', sa.JSON(), nullable=True),
    sa.Column('nearest_public_transportation', sa.JSON(), nullable=True),
    sa.Column('concession_0_bed', sa.Float(), nullable=True),
    sa.Column('concession_1_bed', sa.Float(), nullable=True),
    sa.Column('concession_2_bed', sa.Float(), nullable=True),
    sa.Column('concession_3_bed', sa.Float(), nullable=True),
    sa.Column('concession_additional', sa.Float(), nullable=True),
    sa.Column('concession_title', sa.Text(), nullable=True),
    sa.Column('leasing_type', sa.Text(), nullable=True),
    sa.Column('concession_update', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('flooring', sa.Text(), nullable=True),
    sa.Column('unit_0_balcony', sa.Text(), nullable=True),
    sa.Column('unit_convert_balcony', sa.Text(), nullable=True),
    sa.Column('unit_1_balcony', sa.Text(), nullable=True),
    sa.Column('unit_2_balcony', sa.Text(), nullable=True),
    sa.Column('unit_3_balcony', sa.Text(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('pool', sa.Text(), nullable=True),
    sa.Column('architect', sa.JSON(), nullable=True),
    sa.Column('aptamigo', sa.JSON(), nullable=True),
    sa.Column('hotspot_features', sa.JSON(), nullable=True),
    sa.Column('hotspot_neighbourhood', sa.String(length=250), nullable=True),
    sa.Column('hotspot_description', sa.String(length=250), nullable=True),
    sa.Column('hotspot', sa.JSON(), nullable=True),
    sa.Column('concession_source', sa.Text(), nullable=True),
    sa.Column('walk_score', sa.Integer(), nullable=True),
    sa.Column('walk_score_description', sa.String(length=250), nullable=True),
    sa.Column('walk_score_updated_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('cooperation_percentage_sent', sa.Float(), nullable=True),
    sa.Column('cooperation_fixed', sa.Float(), nullable=True),
    sa.Column('occupancy_perc', sa.String(length=250), nullable=True),
    sa.Column('avg_rent', sa.String(length=250), nullable=True),
    sa.Column('avg_eff_rent', sa.String(length=250), nullable=True),
    sa.Column('avg_price_per_sqft', sa.String(length=250), nullable=True),
    sa.Column('avg_eff_price_per_sqft', sa.String(length=250), nullable=True),
    sa.Column('software_system', sa.String(length=250), nullable=True),
    sa.Column('min_lease_term', sa.Float(), nullable=True),
    sa.Column('year_renovated', sa.String(length=250), nullable=True),
    sa.Column('building_type', sa.String(length=250), nullable=True),
    sa.Column('n_units', sa.Integer(), nullable=True),
    sa.Column('n_stories', sa.Integer(), nullable=True),
    sa.Column('regional_supervisor', sa.String(length=250), nullable=True),
    sa.Column('onsite_mgr', sa.String(length=250), nullable=True),
    sa.Column('section_8', sa.Boolean(), nullable=True),
    sa.Column('pets_allowed', sa.Boolean(), nullable=True),
    sa.Column('dog_allowed', sa.Boolean(), nullable=True),
    sa.Column('cat_allowed', sa.Boolean(), nullable=True),
    sa.Column('bird_allowed', sa.Boolean(), nullable=True),
    sa.Column('pets_details', sa.JSON(), nullable=True),
    sa.Column('approx_price', sa.JSON(), nullable=True),
    sa.Column('cooperation_title', sa.Text(), nullable=True),
    sa.Column('preferred_tour_type', sa.Integer(), nullable=True),
    sa.Column('adjusted_cooperation_percentage', sa.Float(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('showing_instruction', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('building_unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_building_id', sa.Integer(), nullable=False),
    sa.Column('floor', sa.Text(), nullable=True),
    sa.Column('unit_number', sa.Text(), nullable=True),
    sa.Column('beds', sa.Integer(), nullable=True),
    sa.Column('baths', sa.Float(), nullable=True),
    sa.Column('sqft', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('scraped_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('scrape_id', sa.Integer(), nullable=True),
    sa.Column('floorplan', sa.Text(), nullable=True),
    sa.Column('net_price', sa.Float(), nullable=True),
    sa.Column('price_change', sa.Float(), nullable=True),
    sa.Column('source_file', sa.Text(), nullable=True),
    sa.Column('floorplan_fub_id', sa.Integer(), nullable=True),
    sa.Column('available_date', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['fk_building_id'], ['building.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('building_unit')
    op.drop_table('building_info')
    op.drop_table('building')
    # ### end Alembic commands ###
